### ISSUE TITLE
Exits immediately.

### ISSUE THREAD

**Issue by amiga** [Swizpig/ZGloom#11]

**Comment by Swizpig** [comment]
Any output to the console with this debug build?
[debug.zip](https://github.com/Swizpig/ZGloom/files/4251735/debug.zip)

**Comment by Swizpig** [comment]
Nuts, you can't distribute debug versions without the debug VS DLLs.

I don't suppose you're running Digital Guardian on the machine you're on? This seems to dislike SDL2 programs on one of my machines.

**Comment by amiga** [comment]
No im not, shall i run from cli to see errors? really want to try it, i worked on gloom in later yrs :)

**Comment by Swizpig** [comment]
Haha, I wondered if you were that Gareth Murfin. I'll send you a build with the console enabled.

The ISO of Zombie Massacre on Aminet seems to be corrupt, by the way. I've not been able to open it with anything and had to grab it off one of the Aminet CD's on archive.org

**Comment by amiga** [comment]
ah, i havent even put data in the same folder, which is probably the reason lol.

**Comment by amiga** [comment]
apololgies for being so dumb, it works perfectly and I am AMAZED!.. id love to see some resolution options, no fps cap etc, would be nice to see how fast it could run haha, got to try gloom3/zm next!! so amazing! well done.

**Comment by amiga** [comment]
playing gloom3 in it now!.. great!!
