### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by amiga** [Swizpig/ZGloom#12]
Ive barely done much c++ on Windows, is there an IDE I can use to build this? Id love to play around with the code in an ide :)

**Comment by Swizpig** [comment]
I used VS2013 express. I'll add the solution files to the repository.

**Comment by Swizpig** [comment]
Think I should have uploaded everything needed now.  You'll need to modify the includes path (properties/C++/General/Additional Include Directories) and lib paths (properties/Linker/Input)
