### ISSUE TITLE
Great port! Issues and options

### ISSUE THREAD

**Issue by andiweli** [Swizpig/ZGloom#13]
I've set the game to 1280x800 port and rendering - focal to 512.
I experience some flickering when moving fast.

I know the original game had no save-state feature, but do you think it is possible?

Also some setting to start the game fullscreen would be great.

And last but not least - porting it to the Sony PS Vita - an option for you? :)

i7/16GB Ram/GTX1060-6G

**Comment by Swizpig** [comment]
Original game saved between episodes - I'm looking at that and a level select. The very latest code has VSync support, which may help flicker. 

Saving the fullscreen state should be easily possible as well, I'll add that.

**Comment by andiweli** [comment]
What about porting it to PSVITA? Is this possible? Sadly I have less knowledge of coding...

**Comment by andiweli** [comment]
PS VITA Port done by JetStreamSham.
