### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by rdunn418** [Swizpig/ZGloom#14]
Hi, I saw Kinsie post about this and it looks really cool. Unfortunately on my system when I run the exe it brings up a blank window like its going to start and then it closes a couple seconds later. I'm on Win10 64-bit with an i5 / GTX1080, so fairly standard setup. Tried compatibility modes and running as admin, to no avail.

**Comment by Swizpig** [comment]
What game files are you using, and what directory structure do you have for them?

**Comment by rdunn418** [comment]
Never mind, I'm extremely dumb, I didn't get the original game files first. Sorted now! Sorry about that.  The port is really cool btw, can't wait to see it developed further!
