### ISSUE TITLE
SDL2_Mixer : Mix_Quit()

### ISSUE THREAD

**Issue by BeWorld2018** [Swizpig/ZGloom#17]
Hi
In your game yound dont close SDL2_Mixer.

in soundhandler.cpp

```
void Quit() 
{
 Mix_CloseAudio();
 Mix_Quit();
}

```
in soundhandler.h

`void Quit();`

in  ZGLoom.cpp after Config::Save();

`SoundHandler::Quit();`

Thanks
BeWorld

**Comment by Swizpig** [comment]
Oops. Fixed, thanks.
