### ISSUE TITLE
Texture's glitch (black walls)

### ISSUE THREAD

**Issue by nittamituaki** [Swizpig/ZGloom#21]
I've tested several Gloom mods, I came across an issue that some walls become black walls.
See Gloom3's the 5th level of the 1st episode (Storage).
I'll show a picture attached.
![black-walls](https://user-images.githubusercontent.com/63687079/79288240-2aeb9b00-7f01-11ea-9ea3-da6a2b83bc37.png)

**Comment by Swizpig** [comment]
Think I've fixed this, Gloom 3 uses some short (ie, less than 20 textures per family) images that threw things off.

**Comment by nittamituaki** [comment]
Thanks for a reply. BUT my mods (Did IT come from the desert?) also uses many short (less than 20 textures per family), however, no walls become black color.
I came accross that glitch at other mods ("Computer Levels", "Gloomy breed", "Jecht battle"...etc).
These days I was trying making "Jecht Battle"'s textures shows corectly,
unfortunately, I myself can't solve this issue
even if I re-create txt files (e.g. changing # of colors ,etc). I don't know how I can.
By the way, this issue (Black walls) happens exclusively inZGloom.

**Comment by nittamituaki** [comment]
Tested the latest version (uploaded Apr. 19), It seems this issue was fixed in several maps 
(e.g. Gloom3 E1L4, Jecht Battle, AGA Experience Levels #6, and Death Mask level in Czeslaw's first pack).
Yet some textures become black walls at the 2nd & 4th levels of Computer levels, 
Level 1 ~ 4 of Gloomy Breed, and the 1st level of Mini Levels.
Of course I myself don't know why...

**Comment by Swizpig** [comment]
Gnh. Dumb signed/unsigned mixup mean any texture >=128 would not display. Should be fixed.

**Comment by nittamituaki** [comment]
There are no black walls anymore. Thanks!
