### ISSUE TITLE
About player's collision detection the moment he restarts.

### ISSUE THREAD

**Issue by nittamituaki** [Swizpig/ZGloom#22]
After the player is killed, he will restart at the starting point.
At that moment he becomes invincible for few seconds ...in original Amiga version.
In ZGloom, no invincible time is allowed.
It means the player absolutely gets damage if any enemies exist at the starting point.

**Comment by nittamituaki** [comment]
Tested the latest version of ZGloom, Thanks.
Sorry I had forggoten to tell you following fact of Amiga version:
While that invincible 3 seconds, enemies touching the player also don't get damage by touching the player.
I usually call that damage "melee damage";
 = line #449~472 of objectgraphics.cpp.
If the player restarts and enemies also exists at the starting point,
both the player and enemies doen't get melee damage each other in the first 3 seconds.
After that, both of them get melee damage each other.
On the other hand, 
while that invincible 3 seconds, enemies get damages by projectiles Player shot.

Today I surely confirmed Amiga version before this post.

**Comment by nittamituaki** [comment]
Hi, I tested May3 version of zgloom.exe.
Unfortunately a new issue occured.
Player's collision detection is generated at the Player 2's starting point
( even before Player 1 dies once ).
It means that enemies get damages when walk through that point
even though player don't shoot or touch them.

I think Gloom3's the first level (E1L1) would be easier to understand what I said.
![g3-e1-1-0504](https://user-images.githubusercontent.com/63687079/80954684-d325bd00-8e38-11ea-8d18-f06167592ef1.png)

**Comment by Swizpig** [comment]
I suspected this for a while  - sometimes you would hear random screams from enemies for no reason, I'll delete the Player2 object.

**Comment by nittamituaki** [comment]
Tested May 10 version of zgloom.exe. Now I think there's no problem temporarily.
Thanks anyway. I will close this issue. 
But this issue might occur again if ZGloom would become compatible with 2 player mode in future...?
